- name: Check if Amazon Linux
  raw: cat /etc/os-release | grep -q "Amazon Linux"
  register: is_amazon_linux
  changed_when: false
  ignore_errors: true

- name: Install Docker and Git on Amazon Linux
  raw: amazon-linux-extras install -y docker && yum install -y git
  when: is_amazon_linux is succeeded and is_amazon_linux.rc == 0
  ignore_errors: true

- name: Install Docker and Git on other systems
  raw: yum install -y docker git || apt-get update && apt-get install -y docker.io git
  when: is_amazon_linux is failed or is_amazon_linux.rc != 0
  ignore_errors: true

- name: Start and enable Docker
  raw: systemctl start docker && systemctl enable docker
  ignore_errors: true

- name: Add ec2-user to docker group
  raw: usermod -aG docker ec2-user
  ignore_errors: true

- name: Run Jenkins container
  raw: docker ps | grep -q jenkins || docker run -d --name jenkins -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts
  ignore_errors: true