---
- name: Stop existing Jenkins container
  raw: docker stop jenkins || true
  ignore_errors: true

- name: Remove existing Jenkins container
  raw: docker rm jenkins || true
  ignore_errors: true

- name: Create Jenkins data directory
  raw: mkdir -p /home/ec2-user/jenkins_home
  ignore_errors: true

- name: Set permissions for Jenkins data directory
  raw: chown 1000:1000 /home/ec2-user/jenkins_home
  ignore_errors: true

- name: Run optimized Jenkins container
  raw: >
    docker run -d --name jenkins 
    -p 8080:8080 -p 50000:50000 
    -v /home/ec2-user/jenkins_home:/var/jenkins_home 
    -e JAVA_OPTS="-Xmx2g -Xms1g -XX:MaxPermSize=512m -Djava.awt.headless=true" 
    --restart always
    --memory=3g --memory-swap=6g --cpu-shares=2048
    jenkins/jenkins:lts-jdk17
  ignore_errors: true

- name: Wait for Jenkins to start
  raw: sleep 30
  ignore_errors: true

- name: Get Jenkins initial admin password
  raw: docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword || echo "Jenkins may not be fully started yet"
  register: jenkins_password
  ignore_errors: true

- name: Display Jenkins password
  debug:
    var: jenkins_password.stdout_lines
  ignore_errors: true