- name: Install Python dependencies with compatible urllib3
  raw: pip3.8 install 'urllib3<2.0' requests docker
  changed_when: false

- name: Run SonarQube container
  shell: docker run -d --name sonarqube -p 9000:9000 --restart always sonarqube
  args:
    creates: /var/lib/docker/containers/*sonarqube*
  ignore_errors: true

- name: Run Nexus3 container
  shell: docker run -d --name nexus -p 8081:8081 --restart always sonatype/nexus3
  args:
    creates: /var/lib/docker/containers/*nexus*
  ignore_errors: true
