global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flask_dashboard'
    metrics_path: /metrics
    static_configs:
      - targets: ['flask-app-alb-2130422129.us-east-1.elb.amazonaws.com:80']
