global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flask_dashboard'
    metrics_path: /metrics
    static_configs:
      - targets: ['44.203.53.132:80']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
