- name: Check if Amazon Linux
  raw: cat /etc/os-release | grep -q "Amazon Linux"
  register: is_amazon_linux
  changed_when: false
  ignore_errors: true

- name: Install Docker on Amazon Linux
  raw: amazon-linux-extras install -y docker
  when: is_amazon_linux is succeeded and is_amazon_linux.rc == 0
  ignore_errors: true

- name: Install Docker on other systems
  raw: yum install -y docker || apt-get update && apt-get install -y docker.io
  when: is_amazon_linux is failed or is_amazon_linux.rc != 0
  ignore_errors: true

- name: Start and enable Docker
  raw: systemctl start docker && systemctl enable docker
  ignore_errors: true

- name: Run SonarQube container
  raw: docker ps | grep -q sonarqube || docker run -d --name sonarqube -p 9000:9000 sonarqube
  ignore_errors: true