---
- name: Deploy Flask Application
  hosts: flask
  become: yes
  gather_facts: no
  vars:
    app_version: "{{ app_version | default('latest') }}"
    app_dir: /opt/flask_dashboard
    app_user: ec2-user
    app_port: 8000
    prometheus_port: "{{ prometheus_port | default('9090') }}"
  
  roles:
    - flask_app
  
  handlers:
    - name: Reload firewall
      raw: firewall-cmd --reload
      ignore_errors: true
