---
- name: Optimize Jenkins Performance
  hosts: jenkins
  gather_facts: no
  become: yes
  tasks:
    - name: Wait for SSH connection
      raw: echo "Connected"
      register: connection_test
      retries: 10
      delay: 5
      until: connection_test is success

    - name: Check Docker status
      raw: systemctl status docker
      register: docker_status
      ignore_errors: true
      changed_when: false

    - name: Start Docker if not running
      raw: systemctl start docker
      when: docker_status.rc != 0
      ignore_errors: true

    # Include the Jenkins optimization tasks
    - include_tasks: roles/jenkins/tasks/optimize_jenkins.yml

    - name: Install recommended Jenkins plugins
      raw: >
        docker exec jenkins curl -s -X POST 
        -u admin:$(docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword) 
        -H "Content-Type: application/json" 
        -d '{"plugins": ["performance", "disk-usage", "timestamper", "pipeline-utility-steps", "workflow-aggregator"]}' 
        http://localhost:8080/pluginManager/installPlugins
      ignore_errors: true

    - name: Create Jenkins performance tuning script
      raw: |
        cat > /home/ec2-user/jenkins-tune.sh << 'EOF'
        #!/bin/bash
        # Clean up old builds and workspace
        docker exec jenkins find /var/jenkins_home/jobs -type d -name "builds" -exec find {} -type d -name "[0-9]*" -mtime +7 -exec rm -rf {} \; \;
        docker exec jenkins find /var/jenkins_home/jobs -type d -name "workspace" -exec rm -rf {}/* \;
        # Restart Jenkins weekly for memory cleanup
        echo "0 0 * * 0 docker restart jenkins" | crontab -
        EOF
        chmod +x /home/ec2-user/jenkins-tune.sh
      ignore_errors: true

    - name: Schedule Jenkins maintenance script
      raw: echo "0 2 * * * /home/ec2-user/jenkins-tune.sh" | crontab -
      ignore_errors: true

    - name: Get Jenkins URL
      raw: echo "Jenkins URL: http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4):8080"
      register: jenkins_url
      ignore_errors: true

    - name: Display Jenkins URL
      debug:
        var: jenkins_url.stdout_lines
      ignore_errors: true