- name: Configure Flask App Server
  hosts: flask
  become: true
  gather_facts: no
  roles:
    - flask_app

- name: Configure Jenkins Server
  hosts: jenkins
  become: true
  gather_facts: no
  roles:
    - jenkins

- name: Configure SonarQube Server
  hosts: sonarqube
  become: true
  gather_facts: no
  roles:
    - sonarqube

- name: Configure Nexus Server
  hosts: nexus
  become: true
  gather_facts: no
  roles:
    - nexus

- name: Configure Monitoring Stack
  hosts: monitoring
  become: true
  gather_facts: no
  roles:
    - monitoring_stack